cd /home/gimseongsu/shared/QHFlow/src
root="/home/gimseongsu/shared/QHFlow"

python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=1  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=2  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=3  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=4  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=5  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=6  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=7  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=8 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=9  --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=10 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=11 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=12 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=13 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=14 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=15 --split=mol --root="$root/dataset"

conda activate qhflow
cd /home/gimseongsu/shared/QHFlow/_my_scripts
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=16 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=17 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=18 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=19 --split=mol --root="$root/dataset"
python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=20 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=21 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=22 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=23 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=24 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=25 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=26 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=27 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=28 --split=mol --root="$root/dataset"
# python -m dataset_module.qh9_datasets_split --name=QH9Dynamic --num_chunks=30 --chunk_idx=29 --split=mol --root="$root/dataset"
